# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Calin Mocanu
email: calin@mocanu.info
description: >- # this means to ignore newlines until "baseurl:"
  My personal website / blog / resume.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://calin.mocanu.info"
twitter_username: calin_mocanu
github_username:  csiz

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Content options
excerpt_separator: <!--more-->
show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
